spring:
  profiles:
    # dev：开发环境
    # test：测试环境
    # pro：正式环境
    active: ${ACTIVE_PROFILES:dev}
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB

# 该工程不支持文档
knife4j:
  # 自定义变量传给下级环境文件
  supportable: false