package com.im.common.response;

import com.im.common.util.StrUtil;

/**
 * @author Barry
 * @date 2022-03-03
 */
public class TestNewLanguage {
    public static void main(String[] args) {
        String groups = "SMS_TEMPLATE\n" +
                "SMS_TEMPLATE\n" +
                "SMS_TEMPLATE\n" +
                "SMS_TEMPLATE\n" +
                "SMS_TEMPLATE\n" +
                "SMS_TEMPLATE\n" +
                "SMS_TEMPLATE\n" +
                "SMS_TEMPLATE\n" +
                "SMS_TEMPLATE\n" +
                "SMS_TEMPLATE\n" +
                "SMS_TEMPLATE\n" +
                "SMS_TEMPLATE\n" +
                "SMS_TEMPLATE\n" +
                "SMS_TEMPLATE\n" +
                "SMS_TEMPLATE\n" +
                "SMS_TEMPLATE\n" +
                "SMS_TEMPLATE\n" +
                "SMS_TEMPLATE\n" +
                "SMS_TEMPLATE\n" +
                "SMS_TEMPLATE\n" +
                "SMS_TEMPLATE\n" +
                "SMS_TEMPLATE\n" +
                "SMS_TEMPLATE\n" +
                "SMS_TEMPLATE\n" +
                "SMS_TEMPLATE\n" +
                "SMS_TEMPLATE\n" +
                "SMS_TEMPLATE\n" +
                "SMS_TEMPLATE\n" +
                "SMS_TEMPLATE\n" +
                "SMS_TEMPLATE\n" +
                "SMS_TEMPLATE\n" +
                "SMS_TEMPLATE\n" +
                "SMS_TEMPLATE\n" +
                "SMS_TEMPLATE\n" +
                "SMS_TEMPLATE\n" +
                "SMS_TEMPLATE\n" +
                "SMS_TEMPLATE\n" +
                "SMS_TEMPLATE\n" +
                "SMS_TEMPLATE\n" +
                "SMS_TEMPLATE\n" +
                "SMS_TEMPLATE\n" +
                "SMS_TEMPLATE\n" +
                "SMS_TEMPLATE\n" +
                "SMS_TEMPLATE\n" +
                "SMS_TEMPLATE\n" +
                "SMS_TEMPLATE\n" +
                "SMS_TEMPLATE\n" +
                "SMS_TEMPLATE\n" +
                "SMS_TEMPLATE\n" +
                "SMS_TEMPLATE\n" +
                "SMS_TEMPLATE\n" +
                "SMS_TEMPLATE\n" +
                "SMS_TEMPLATE\n" +
                "SMS_TEMPLATE\n" +
                "SMS_TEMPLATE\n" +
                "SMS_TEMPLATE\n" +
                "SMS_TEMPLATE\n" +
                "SMS_TEMPLATE\n" +
                "SMS_TEMPLATE\n" +
                "SMS_TEMPLATE\n" +
                "SMS_TEMPLATE\n" +
                "SMS_TEMPLATE\n" +
                "SMS_TEMPLATE\n" +
                "SMS_TEMPLATE\n" +
                "SMS_TEMPLATE\n" +
                "SMS_TEMPLATE\n" +
                "SMS_TEMPLATE\n" +
                "SMS_TEMPLATE\n" +
                "SMS_TEMPLATE\n" +
                "SMS_TEMPLATE\n" +
                "SMS_TEMPLATE\n" +
                "SMS_TEMPLATE\n" +
                "SMS_TEMPLATE\n" +
                "SMS_TEMPLATE\n" +
                "SMS_TEMPLATE\n" +
                "SMS_TEMPLATE\n" +
                "SMS_TEMPLATE\n" +
                "SMS_TEMPLATE\n" +
                "SMS_TEMPLATE\n" +
                "SMS_TEMPLATE\n" +
                "SMS_TEMPLATE\n" +
                "SMS_TEMPLATE\n" +
                "SMS_TEMPLATE\n" +
                "SMS_TEMPLATE\n" +
                "SMS_TEMPLATE\n" +
                "SMS_TEMPLATE\n" +
                "SMS_TEMPLATE\n" +
                "SMS_TEMPLATE\n" +
                "SMS_TEMPLATE\n" +
                "SMS_TEMPLATE\n" +
                "SMS_TEMPLATE\n" +
                "SMS_TEMPLATE\n" +
                "SMS_TEMPLATE\n" +
                "SMS_TEMPLATE\n" +
                "SMS_TEMPLATE\n" +
                "SMS_TEMPLATE\n" +
                "SMS_TEMPLATE\n" +
                "SMS_TEMPLATE\n" +
                "SMS_TEMPLATE\n" +
                "SMS_TEMPLATE\n" +
                "SMS_TEMPLATE\n" +
                "SMS_TEMPLATE\n" +
                "SMS_TEMPLATE\n" +
                "SMS_TEMPLATE\n" +
                "SMS_TEMPLATE\n" +
                "SMS_TEMPLATE\n" +
                "SMS_TEMPLATE\n" +
                "SMS_TEMPLATE\n" +
                "SMS_TEMPLATE\n" +
                "SMS_TEMPLATE\n" +
                "SMS_TEMPLATE\n" +
                "SMS_TEMPLATE\n" +
                "SMS_TEMPLATE\n" +
                "SMS_TEMPLATE\n" +
                "SMS_TEMPLATE\n" +
                "SMS_TEMPLATE\n" +
                "SMS_TEMPLATE\n" +
                "SMS_TEMPLATE\n" +
                "SMS_TEMPLATE\n" +
                "SMS_TEMPLATE\n" +
                "SMS_TEMPLATE\n" +
                "SMS_TEMPLATE\n" +
                "SMS_TEMPLATE\n" +
                "SMS_TEMPLATE\n" +
                "SMS_TEMPLATE\n" +
                "SMS_TEMPLATE\n" +
                "SMS_TEMPLATE\n" +
                "SMS_TEMPLATE\n" +
                "SMS_TEMPLATE\n" +
                "SMS_TEMPLATE\n" +
                "SMS_TEMPLATE\n" +
                "SMS_TEMPLATE\n" +
                "SMS_TEMPLATE\n" +
                "SMS_TEMPLATE\n" +
                "SMS_TEMPLATE\n" +
                "SMS_TEMPLATE\n" +
                "SMS_TEMPLATE\n" +
                "SMS_TEMPLATE\n" +
                "SMS_TEMPLATE\n" +
                "SMS_TEMPLATE\n" +
                "SMS_TEMPLATE\n" +
                "SMS_TEMPLATE\n" +
                "SMS_TEMPLATE\n" +
                "SMS_TEMPLATE\n" +
                "SMS_TEMPLATE\n" +
                "SMS_TEMPLATE\n" +
                "SMS_TEMPLATE\n" +
                "SMS_TEMPLATE\n" +
                "SMS_TEMPLATE\n" +
                "SMS_TEMPLATE\n" +
                "SMS_TEMPLATE\n" +
                "SMS_TEMPLATE\n" +
                "SMS_TEMPLATE\n" +
                "SMS_TEMPLATE\n" +
                "SMS_TEMPLATE\n" +
                "SMS_TEMPLATE\n" +
                "SMS_TEMPLATE\n" +
                "SMS_TEMPLATE\n" +
                "SMS_TEMPLATE\n" +
                "SMS_TEMPLATE\n" +
                "SMS_TEMPLATE\n" +
                "SMS_TEMPLATE\n" +
                "SMS_TEMPLATE\n" +
                "SMS_TEMPLATE\n" +
                "SMS_TEMPLATE\n" +
                "SMS_TEMPLATE\n" +
                "SMS_TEMPLATE\n" +
                "SMS_TEMPLATE\n" +
                "SMS_TEMPLATE\n" +
                "SMS_TEMPLATE\n" +
                "SMS_TEMPLATE\n" +
                "SMS_TEMPLATE\n" +
                "SMS_TEMPLATE\n" +
                "SMS_TEMPLATE\n" +
                "SMS_TEMPLATE\n" +
                "SMS_TEMPLATE\n" +
                "SMS_TEMPLATE\n" +
                "SMS_TEMPLATE\n" +
                "SMS_TEMPLATE\n" +
                "SMS_TEMPLATE\n" +
                "SMS_TEMPLATE\n" +
                "SMS_TEMPLATE\n" +
                "SMS_TEMPLATE\n" +
                "SMS_TEMPLATE\n" +
                "SMS_TEMPLATE\n" +
                "SMS_TEMPLATE\n" +
                "SMS_TEMPLATE\n" +
                "SMS_TEMPLATE\n" +
                "SMS_TEMPLATE\n" +
                "SMS_TEMPLATE\n" +
                "SMS_TEMPLATE\n" +
                "SMS_TEMPLATE\n" +
                "SMS_TEMPLATE\n" +
                "SMS_TEMPLATE\n" +
                "SMS_TEMPLATE\n" +
                "SMS_TEMPLATE\n" +
                "SMS_TEMPLATE\n" +
                "SMS_TEMPLATE\n" +
                "SMS_TEMPLATE\n" +
                "SMS_TEMPLATE\n" +
                "SMS_TEMPLATE\n" +
                "SMS_TEMPLATE\n" +
                "SMS_TEMPLATE\n" +
                "SMS_TEMPLATE\n" +
                "SMS_TEMPLATE\n" +
                "SMS_TEMPLATE\n" +
                "SMS_TEMPLATE\n" +
                "SMS_TEMPLATE\n" +
                "SMS_TEMPLATE\n" +
                "SMS_TEMPLATE\n" +
                "SMS_TEMPLATE\n" +
                "SMS_TEMPLATE\n" +
                "SMS_TEMPLATE\n" +
                "SMS_TEMPLATE\n" +
                "SMS_TEMPLATE\n" +
                "SMS_TEMPLATE\n" +
                "RSP_MSG\n" +
                "RSP_MSG\n" +
                "RSP_MSG\n" +
                "RSP_MSG\n" +
                "RSP_MSG\n" +
                "RSP_MSG\n" +
                "RSP_MSG\n" +
                "RSP_MSG\n" +
                "RSP_MSG\n" +
                "RSP_MSG\n" +
                "RSP_MSG\n" +
                "RSP_MSG\n" +
                "RSP_MSG\n" +
                "RSP_MSG\n" +
                "RSP_MSG\n" +
                "RSP_MSG\n" +
                "RSP_MSG\n" +
                "RSP_MSG\n" +
                "RSP_MSG\n" +
                "RSP_MSG\n" +
                "RSP_MSG\n" +
                "RSP_MSG\n" +
                "RSP_MSG\n" +
                "RSP_MSG\n" +
                "RSP_MSG\n" +
                "RSP_MSG\n" +
                "RSP_MSG\n" +
                "RSP_MSG\n" +
                "RSP_MSG\n" +
                "RSP_MSG\n" +
                "RSP_MSG\n" +
                "RSP_MSG\n" +
                "RSP_MSG\n" +
                "RSP_MSG\n" +
                "RSP_MSG\n" +
                "RSP_MSG\n" +
                "RSP_MSG\n" +
                "RSP_MSG\n" +
                "RSP_MSG\n" +
                "RSP_MSG\n" +
                "RSP_MSG\n" +
                "RSP_MSG\n" +
                "RSP_MSG\n" +
                "RSP_MSG\n" +
                "RSP_MSG\n" +
                "RSP_MSG\n" +
                "RSP_MSG\n" +
                "RSP_MSG\n" +
                "RSP_MSG\n" +
                "RSP_MSG\n" +
                "RSP_MSG\n" +
                "RSP_MSG\n" +
                "RSP_MSG\n" +
                "RSP_MSG\n" +
                "RSP_MSG\n" +
                "RSP_MSG\n" +
                "RSP_MSG\n" +
                "RSP_MSG\n" +
                "RSP_MSG\n" +
                "RSP_MSG\n" +
                "RSP_MSG\n" +
                "RSP_MSG\n" +
                "RSP_MSG\n" +
                "RSP_MSG\n" +
                "RSP_MSG\n" +
                "RSP_MSG\n" +
                "RSP_MSG\n" +
                "RSP_MSG\n" +
                "RSP_MSG\n" +
                "RSP_MSG\n" +
                "RSP_MSG\n" +
                "RSP_MSG\n" +
                "RSP_MSG\n" +
                "RSP_MSG\n" +
                "RSP_MSG\n" +
                "RSP_MSG\n" +
                "RSP_MSG\n" +
                "RSP_MSG\n" +
                "RSP_MSG\n" +
                "RSP_MSG\n" +
                "RSP_MSG\n" +
                "RSP_MSG\n" +
                "RSP_MSG\n" +
                "RSP_MSG\n" +
                "RSP_MSG\n" +
                "RSP_MSG\n" +
                "RSP_MSG\n" +
                "RSP_MSG\n" +
                "RSP_MSG\n" +
                "RSP_MSG\n" +
                "RSP_MSG\n" +
                "RSP_MSG\n" +
                "RSP_MSG\n" +
                "RSP_MSG\n" +
                "RSP_MSG\n" +
                "RSP_MSG\n" +
                "RSP_MSG\n" +
                "RSP_MSG\n" +
                "RSP_MSG\n" +
                "RSP_MSG\n" +
                "RSP_MSG\n" +
                "RSP_MSG\n" +
                "RSP_MSG\n" +
                "RSP_MSG\n" +
                "RSP_MSG\n" +
                "RSP_MSG\n" +
                "RSP_MSG\n" +
                "RSP_MSG\n" +
                "RSP_MSG\n" +
                "RSP_MSG\n" +
                "RSP_MSG\n" +
                "RSP_MSG\n" +
                "RSP_MSG\n" +
                "RSP_MSG\n" +
                "RSP_MSG\n" +
                "RSP_MSG\n" +
                "RSP_MSG\n" +
                "RSP_MSG\n" +
                "RSP_MSG\n" +
                "RSP_MSG\n" +
                "RSP_MSG\n" +
                "RSP_MSG\n" +
                "RSP_MSG\n" +
                "RSP_MSG\n" +
                "RSP_MSG\n" +
                "RSP_MSG\n" +
                "RSP_MSG\n" +
                "RSP_MSG\n" +
                "RSP_MSG\n" +
                "RSP_MSG\n" +
                "RSP_MSG\n" +
                "RSP_MSG\n" +
                "RSP_MSG\n" +
                "RSP_MSG\n" +
                "RSP_MSG\n" +
                "RSP_MSG\n" +
                "RSP_MSG\n" +
                "RSP_MSG\n" +
                "RSP_MSG\n" +
                "RSP_MSG\n" +
                "RSP_MSG\n" +
                "RSP_MSG\n" +
                "RSP_MSG\n" +
                "RSP_MSG\n" +
                "RSP_MSG\n" +
                "RSP_MSG\n" +
                "RSP_MSG\n" +
                "RSP_MSG\n" +
                "RSP_MSG\n" +
                "RSP_MSG\n" +
                "RSP_MSG\n" +
                "RSP_MSG\n" +
                "RSP_MSG\n" +
                "RSP_MSG\n" +
                "RSP_MSG\n" +
                "RSP_MSG\n" +
                "RSP_MSG\n" +
                "RSP_MSG\n" +
                "RSP_MSG\n" +
                "RSP_MSG\n" +
                "RSP_MSG\n" +
                "ADMIN_MENU\n" +
                "ADMIN_MENU\n" +
                "ADMIN_MENU\n" +
                "ADMIN_MENU\n" +
                "ADMIN_MENU\n" +
                "ADMIN_MENU\n" +
                "ADMIN_MENU\n" +
                "ADMIN_MENU\n" +
                "ADMIN_MENU\n" +
                "ADMIN_MENU\n" +
                "ADMIN_MENU\n" +
                "ADMIN_MENU\n" +
                "ADMIN_MENU\n" +
                "ADMIN_MENU\n" +
                "ADMIN_MENU\n" +
                "ADMIN_MENU\n" +
                "ADMIN_MENU\n" +
                "ADMIN_MENU\n" +
                "ADMIN_MENU\n" +
                "ADMIN_MENU\n" +
                "ADMIN_MENU\n" +
                "ADMIN_MENU\n" +
                "ADMIN_MENU\n" +
                "ADMIN_MENU\n" +
                "ADMIN_MENU\n" +
                "ADMIN_MENU\n" +
                "ADMIN_MENU\n" +
                "ADMIN_MENU\n" +
                "ADMIN_MENU\n" +
                "ADMIN_MENU\n" +
                "ADMIN_MENU\n" +
                "ADMIN_MENU\n" +
                "ADMIN_MENU\n" +
                "ADMIN_MENU\n" +
                "ADMIN_MENU\n" +
                "ADMIN_MENU\n" +
                "ADMIN_MENU\n" +
                "ADMIN_MENU\n" +
                "ADMIN_MENU\n" +
                "ADMIN_MENU\n" +
                "ADMIN_MENU\n" +
                "ADMIN_MENU\n" +
                "ADMIN_MENU\n" +
                "ADMIN_MENU\n" +
                "ADMIN_MENU\n" +
                "ADMIN_MENU\n" +
                "ADMIN_MENU\n" +
                "ADMIN_MENU\n" +
                "ADMIN_MENU\n" +
                "ADMIN_MENU\n" +
                "ADMIN_MENU\n" +
                "ADMIN_MENU\n" +
                "ADMIN_MENU\n" +
                "ADMIN_MENU\n" +
                "ADMIN_MENU\n" +
                "ADMIN_MENU\n" +
                "ADMIN_MENU\n" +
                "ADMIN_MENU\n" +
                "ADMIN_MENU\n" +
                "ADMIN_MENU\n" +
                "ADMIN_MENU\n" +
                "ADMIN_MENU\n" +
                "ADMIN_MENU\n" +
                "ADMIN_MENU\n" +
                "ADMIN_MENU\n" +
                "ADMIN_MENU\n" +
                "ADMIN_MENU\n" +
                "ADMIN_MENU\n" +
                "ADMIN_MENU\n" +
                "ADMIN_MENU\n" +
                "ADMIN_MENU\n" +
                "ADMIN_MENU\n" +
                "ADMIN_MENU\n" +
                "ADMIN_MENU\n" +
                "ADMIN_MENU\n" +
                "ADMIN_MENU\n" +
                "ADMIN_MENU\n" +
                "ADMIN_MENU\n" +
                "ADMIN_MENU\n" +
                "ADMIN_MENU\n" +
                "ADMIN_MENU\n" +
                "ADMIN_MENU\n" +
                "ADMIN_MENU\n" +
                "ADMIN_MENU";

        String codes = "AF\n" +
                "AL\n" +
                "DZ\n" +
                "AS\n" +
                "AD\n" +
                "AO\n" +
                "AI\n" +
                "AG\n" +
                "AR\n" +
                "AM\n" +
                "AW\n" +
                "AU\n" +
                "AT\n" +
                "AZ\n" +
                "BS\n" +
                "BH\n" +
                "BD\n" +
                "BB\n" +
                "BY\n" +
                "BE\n" +
                "BZ\n" +
                "BJ\n" +
                "BM\n" +
                "BT\n" +
                "BO\n" +
                "BA\n" +
                "BW\n" +
                "BR\n" +
                "BN\n" +
                "BG\n" +
                "BF\n" +
                "BI\n" +
                "KH\n" +
                "CM\n" +
                "CA\n" +
                "CV\n" +
                "KY\n" +
                "CF\n" +
                "TD\n" +
                "CL\n" +
                "CHN\n" +
                "CO\n" +
                "KM\n" +
                "CK\n" +
                "CR\n" +
                "HR\n" +
                "CU\n" +
                "CW\n" +
                "CY\n" +
                "CZ\n" +
                "CD\n" +
                "DK\n" +
                "DJ\n" +
                "DM\n" +
                "DO\n" +
                "TL\n" +
                "EC\n" +
                "EG\n" +
                "SV\n" +
                "GQ\n" +
                "ER\n" +
                "EE\n" +
                "ET\n" +
                "FO\n" +
                "FJ\n" +
                "FI\n" +
                "FR\n" +
                "GF\n" +
                "PF\n" +
                "GA\n" +
                "GM\n" +
                "GE\n" +
                "DE\n" +
                "GH\n" +
                "GI\n" +
                "GR\n" +
                "GL\n" +
                "GD\n" +
                "GP\n" +
                "GU\n" +
                "GT\n" +
                "GN\n" +
                "GW\n" +
                "GY\n" +
                "HT\n" +
                "HN\n" +
                "HK\n" +
                "HU\n" +
                "IS\n" +
                "IN\n" +
                "ID\n" +
                "IR\n" +
                "IQ\n" +
                "IE\n" +
                "IL\n" +
                "IT\n" +
                "CI\n" +
                "JM\n" +
                "JP\n" +
                "JO\n" +
                "KZ\n" +
                "KE\n" +
                "KI\n" +
                "KW\n" +
                "KG\n" +
                "LA\n" +
                "LV\n" +
                "LB\n" +
                "LS\n" +
                "LR\n" +
                "LY\n" +
                "LI\n" +
                "LT\n" +
                "LU\n" +
                "MO\n" +
                "MK\n" +
                "MG\n" +
                "MW\n" +
                "MY\n" +
                "MV\n" +
                "ML\n" +
                "MT\n" +
                "MQ\n" +
                "MR\n" +
                "MU\n" +
                "YT\n" +
                "MX\n" +
                "MD\n" +
                "MC\n" +
                "MN\n" +
                "ME\n" +
                "MS\n" +
                "MA\n" +
                "MZ\n" +
                "MM\n" +
                "NA\n" +
                "NP\n" +
                "NL\n" +
                "NC\n" +
                "NZ\n" +
                "NI\n" +
                "NE\n" +
                "NG\n" +
                "NO\n" +
                "OM\n" +
                "PK\n" +
                "PW\n" +
                "BL\n" +
                "PA\n" +
                "PG\n" +
                "PY\n" +
                "PE\n" +
                "PH\n" +
                "PL\n" +
                "PT\n" +
                "PR\n" +
                "QA\n" +
                "CG\n" +
                "RE\n" +
                "RO\n" +
                "RU\n" +
                "RW\n" +
                "KN\n" +
                "LC\n" +
                "PM\n" +
                "VC\n" +
                "WS\n" +
                "SM\n" +
                "ST\n" +
                "SA\n" +
                "SN\n" +
                "RS\n" +
                "SC\n" +
                "SL\n" +
                "SG\n" +
                "SX\n" +
                "SK\n" +
                "SI\n" +
                "SB\n" +
                "SO\n" +
                "ZA\n" +
                "KR\n" +
                "ES\n" +
                "LK\n" +
                "SD\n" +
                "SR\n" +
                "SZ\n" +
                "SE\n" +
                "CH\n" +
                "SY\n" +
                "TW\n" +
                "TJ\n" +
                "TZ\n" +
                "TH\n" +
                "TG\n" +
                "TO\n" +
                "TT\n" +
                "TN\n" +
                "TR\n" +
                "TM\n" +
                "TC\n" +
                "UG\n" +
                "UA\n" +
                "UAE\n" +
                "GB\n" +
                "US\n" +
                "UY\n" +
                "UZ\n" +
                "VU\n" +
                "VE\n" +
                "VN\n" +
                "VG\n" +
                "VI\n" +
                "YE\n" +
                "ZM\n" +
                "ZW\n" +
                "PASSWORD_REQUIRED\n" +
                "PAGE_PARAM_ERROR\n" +
                "USERNAME_REQUIRED\n" +
                "SYS_REQUEST_PARAM_ERROR\n" +
                "GOOGLE_CODE_REQUIRED\n" +
                "TOKEN_REQUIRED\n" +
                "IP_FORMATTING_INCORRECT\n" +
                "TIMESTAMP_REQUIRED\n" +
                "TIMESTAMP_EXPIRED\n" +
                "SYS_SERVER_ERROR\n" +
                "SYS_NO_SUCH_METHOD\n" +
                "SYS_CONTENT_TYPE_ERROR\n" +
                "SYS_NO_PERMISSION\n" +
                "SYS_METHOD_UNDER_CONSTRUCTION\n" +
                "SYS_REQUEST_REPEAT\n" +
                "SYS_REQUEST_REPEAT_BY_IP\n" +
                "SYS_REQUEST_ACQUIRE_LOCK_FAILED\n" +
                "SYS_REQUEST_PARAM_MISSING\n" +
                "SYS_REQUEST_ILLEGAL\n" +
                "SYS_REQUEST_PARAM_ILLEGAL\n" +
                "SYS_REQUEST_PROCESSING\n" +
                "SYS_REQUEST_TIMEOUT\n" +
                "SYS_REQUEST_LIMITED\n" +
                "SYS_DATA_STATUS_ERROR\n" +
                "SYS_DATA_NOT_EDITABLE\n" +
                "SYS_DATA_DELETED\n" +
                "SYS_DATA_EXISTED\n" +
                "SYS_DATA_NOT_EXIST\n" +
                "SYS_DATA_NOT_EXIST_OR_EXPIRED\n" +
                "SYS_DATA_SAME_DATABASE\n" +
                "IP_NOT_ILLEGAL_IPV4_IPV4MASK_IPV6\n" +
                "AREA_NOT_ALLOWED\n" +
                "SYS_ONLY_ONE_REQUEST_AT_SAME_TIME\n" +
                "SYS_DATA_ALREADY_FIRST\n" +
                "SYS_DATA_ALREADY_LAST\n" +
                "SYS_AMOUNT_INCORRECT\n" +
                "SYS_AMOUNT_NO_PRECISION\n" +
                "SYS_AMOUNT_MAX_PRECISION_INCORRECT\n" +
                "SYS_AMOUNT_NOT_IN_RANGE\n" +
                "SYS_AMOUNT_RANGE_FORMATTING_INCORRECT\n" +
                "SYS_TIME_RANGE_FORMATTING_INCORRECT\n" +
                "OSS_CONNECT_ERROR\n" +
                "SYS_UPLOAD_FILE_NOT_EMPTY\n" +
                "SYS_UPLOAD_FILE_ERROR\n" +
                "SYS_UPLOAD_FILE_ONLY_ACCEPT_JPG_OR_PNG\n" +
                "SYS_UPLOAD_FILE_SIZE_EXCEEDED\n" +
                "SYS_MAX_QUERY_PAST_DAY\n" +
                "SYS_EXPORT_DATETIME_RANGE_EXCEEDED\n" +
                "SYS_REMARK_REQUIRED\n" +
                "IM_CONNECT_EXCEPTION\n" +
                "IM_EXECUTE_EXCEPTION\n" +
                "ADMIN_ROLE_NAME_EXISTED\n" +
                "ADMIN_ROLE_NOT_SELF_OR_LOWER_ROLE\n" +
                "ADMIN_ROLE_NOT_LOWER\n" +
                "YOUR_ACCOUNT_HAS_BEEN_DISABLED\n" +
                "YOUR_ACCOUNT_LOGIN_HAS_BEEN_DISABLED\n" +
                "YOUR_ACCOUNT_RECHARGE_HAS_BEEN_DISABLED\n" +
                "YOUR_ACCOUNT_WITHDRAW_HAS_BEEN_DISABLED\n" +
                "USER_ALREADY_LOGIN\n" +
                "USER_LOGIN_USERNAME_OR_PASSWORD_ERROR\n" +
                "USER_LOGIN_USERNAME_OR_PASSWORD_ERROR_LEFT_TIME\n" +
                "USER_LOGIN_TOO_MANY_PWD_ERROR_TIMES\n" +
                "USER_ROLE_DISABLED\n" +
                "USER_ROLE_ILLEGAL\n" +
                "USER_NOT_FOUND\n" +
                "USER_INSUFFICIENT_BALANCE\n" +
                "GOOGLE_CODE_ERROR\n" +
                "GOOGLE_CODE_DUPLICATED\n" +
                "GOOGLE_ALREADY_BIND\n" +
                "GOOGLE_NOT_YET_BIND\n" +
                "USER_USERNAME_EXISTED\n" +
                "USER_NOT_ALLOW_OPERATE_SELF\n" +
                "USER_NOT_ALLOW_ADMIN\n" +
                "USER_SESSION_FORCE_LOGOUT\n" +
                "USER_SESSION_OTHER_LOGIN\n" +
                "USER_SESSION_INFO_CHANGED\n" +
                "USER_SESSION_INVALIDATE\n" +
                "USER_SESSION_EXPIRED\n" +
                "USER_SESSION_PLEASE_LOGIN_FIRST\n" +
                "USER_SESSION_TOKEN_MISSING\n" +
                "USER_SESSION_TOKEN_INVALID\n" +
                "USER_OLD_PASSWORD_INCORRECT\n" +
                "USER_PASSWORD_ALREADY_BOUND\n" +
                "USER_NEW_PWD_MUST_DIFFERENT_OLD\n" +
                "USER_FUND_PASSWORD_NOT_YET_BIND\n" +
                "USER_FUND_PASSWORD_INCORRECT\n" +
                "USER_FUND_PWD_MUST_DIFFERENT_LOGIN_PWD\n" +
                "USER_RECHARGE_DISABLED\n" +
                "USER_WITHDRAW_DISABLED\n" +
                "USER_REGISTER_INVITE_CODE_EXCEEDED\n" +
                "USER_REGISTER_DISABLED\n" +
                "USER_REGISTER_LIMIT_COUNT_BY_IP_EXCEEDED\n" +
                "USER_REGISTER_INVITE_CODE_REQUIRED\n" +
                "USER_REGISTER_INVITE_CODE_NOT_FOUND\n" +
                "USER_REGISTER_INVITE_CODE_DISABLED\n" +
                "USER_REGISTER_MOBILE_REQUIRED\n" +
                "USER_REGISTER_MOBILE_REPEAT\n" +
                "USER_REGISTER_MOBILE_VERIFICATION_CODE_REQUIRED\n" +
                "USER_REGISTER_FUND_PWD_REQUIRED\n" +
                "INVITE_CODE_NOT_FOUND\n" +
                "USER_WITHDRAW_NAME_MUST_BE_CHINESE\n" +
                "USER_WITHDRAW_NAME_ALREADY_BOUND\n" +
                "USER_WITHDRAW_NAME_NOT_YET_BIND\n" +
                "NOT_YOUR_FRIEND\n" +
                "RECHARGE_NO_CARD_FOUND\n" +
                "RECHARGE_USER_CARD_NAME_REQUIRED\n" +
                "WITHDRAW_MAX_DAILY_REQUEST_EXCEEDED\n" +
                "WITHDRAW_MAX_SAME_TIME_REQUEST_EXCEEDED\n" +
                "WITHDRAW_LIMIT_NOT_YET_FINISH\n" +
                "WITHDRAW_NOT_IN_ENABLE_TIME\n" +
                "API_RECHARGE_CONFIG_NOT_FOUND\n" +
                "API_RECHARGE_THIRD_CONFIG_FORMATTING_INCORRECT\n" +
                "API_RECHARGE_HANDLER_NOT_FOUND\n" +
                "API_RECHARGE_REQUEST_EXCEPTION\n" +
                "API_RECHARGE_REQUEST_RETURN_FAILED\n" +
                "API_RECHARGE_CALLBACK_PROCESS_FAILED\n" +
                "API_WITHDRAW_CONFIG_NOT_FOUND\n" +
                "API_WITHDRAW_THIRD_CONFIG_FORMATTING_INCORRECT\n" +
                "API_WITHDRAW_CONFIG_DISABLED\n" +
                "API_WITHDRAW_HANDLER_NOT_FOUND\n" +
                "API_WITHDRAW_REQUEST_EXCEPTION\n" +
                "API_WITHDRAW_REQUEST_RETURN_FAILED\n" +
                "API_WITHDRAW_CALLBACK_PROCESS_FAILED\n" +
                "BANK_NOT_FOUND\n" +
                "BANK_DISABLED\n" +
                "BANK_NAME_EXISTED\n" +
                "BANK_CODE_EXISTED\n" +
                "USER_BANK_CARD_NUM_IN_BLACKLIST\n" +
                "USER_BANK_CARD_CARD_NUM_EXISTED\n" +
                "USER_BANK_CARD_REQUIRED\n" +
                "BANK_WITHDRAW_DISABLED\n" +
                "USER_BANK_CARD_MAX_BIND_COUNT_EXCEEDED\n" +
                "USER_BANK_CARD_NOT_YET_BIND\n" +
                "USER_BANK_CARD_NOT_FOUND\n" +
                "USER_BANK_CARD_DISABLED\n" +
                "USER_MOMENTS_EXCEED_IMG_COUNT\n" +
                "USER_MOMENTS_NOT_READ\n" +
                "USER_MOMENTS_ALLOW\n" +
                "USER_MOMENTS_REJECT\n" +
                "REPORT_DATA_MAX_SEARCH_DAY\n" +
                "REPORT_DATE_ERROR\n" +
                "REPORT_USER_EXISTED\n" +
                "I18N_LANGUAGE_LIST_NOT_AVAILABLE\n" +
                "I18N_LANGUAGE_NOT_AVAILABLE\n" +
                "ENVELOPE_EXPIRED\n" +
                "ENVELOPE_RECEIVED\n" +
                "ENVELOPE_ALL_RECEIVED\n" +
                "ENVELOPE_NOT_TO_SELF\n" +
                "ENVELOPE_MAX_NUM_INCORRECT\n" +
                "ENVELOPE_AVERAGE_AMOUNT_INCORRECT\n" +
                "USER_IN_GROUP_CONFLICT\n" +
                "MESSAGE_CAN_NOT_WITHDRAW\n" +
                "USER_NOT_IN_GROUP\n" +
                "USER_GROUP_ALL_SHUTTING_UP\n" +
                "USER_GROUP_SHUTTING_UP\n" +
                "SMS_THIRD_CONNECT_EXCEPTION\n" +
                "SMS_THIRD_CONNECT_INCORRECT\n" +
                "SMS_VERIFICATION_CODE_EXPIRED\n" +
                "SMS_VERIFICATION_CODE_INCORRECT\n" +
                "SMS_COUNTRY_NOT_SUPPORT\n" +
                "APP_VERSION_CODE_MUST_INCREASE\n" +
                "REPORT_MANAGER\n" +
                "USER_MANAGER\n" +
                "FINANCIAL_MANAGER\n" +
                "RED_ENVELOPE\n" +
                "IM_MANAGER\n" +
                "SYS_NOTICE_MANAGER\n" +
                "SYSTEM_MANAGER\n" +
                "ADMIN_MANAGER\n" +
                "USER_LOGIN_LOG\n" +
                "USER_OPERATION_LOG\n" +
                "USER_BILL\n" +
                "USER_BANK_CARD_BLACK\n" +
                "USER_AREA_BLACK_WHITE\n" +
                "USER_IP_BLACK_WHITE\n" +
                "USER_BALANCE_SNAPHSOT\n" +
                "USER_BANK_CARD\n" +
                "USER_MOMENT\n" +
                "USER_RECHARGE_ORDER\n" +
                "USER_WITHDRAW_ORDER\n" +
                "BANK_CARD_RECHARGE_CONFIG\n" +
                "API_RECHARGE_CONFIG\n" +
                "BANK_CARD_WITHDRAW_CONFIG\n" +
                "API_WITHDRAW_CONFIG\n" +
                "PERSONAL_RED_ENVELOPE\n" +
                "GROUP_RED_ENVELOPE\n" +
                "GROUP_MANAGER\n" +
                "USER_CONTACT\n" +
                "USER_ONLINE\n" +
                "USER_C2C_MESSAGE\n" +
                "USER_GROUP_MESSAGE\n" +
                "SYSTEM_CONFIG\n" +
                "SYSTEM_ADVANCE_CONFIG\n" +
                "SYSTEM_BACKUP_CONFIG\n" +
                "BANK_MANAGER\n" +
                "SWITCH_APP\n" +
                "APP_VERSION\n" +
                "ADMIN_USER_MANAGER\n" +
                "ADMIN_ROLE_MANAGER\n" +
                "ADMIN_MENU_MANAGER\n" +
                "ADMIN_LOGIN_LOG\n" +
                "ADMIN_OPERATION_LOG\n" +
                "ADMIN_IP_BLACK_WHITE\n" +
                "LIST\n" +
                "ADD\n" +
                "EDIT\n" +
                "ENABLE_DISABLE_LOGIN\n" +
                "ENABLE_DISABLE_ADD_FRIEND\n" +
                "ENABLE_DISABLE_RECHARGE\n" +
                "ENABLE_DISABLE_WITHDRAW\n" +
                "RESET_FUND_PWD\n" +
                "EDIT_WITHDRAW_NAME\n" +
                "EXPORT\n" +
                "DELETE\n" +
                "ENABLE_DISABLE\n" +
                "DELETE_COMMENT\n" +
                "DELETE_LIKE\n" +
                "PATCH_ORDER\n" +
                "ADMIN_RECHARGE\n" +
                "APPROVE\n" +
                "PAY\n" +
                "ADMIN_WITHDRAW\n" +
                "UNBIND_GOOGLE\n" +
                "RESET_LOGIN_PWD_ERROR_TIMES\n" +
                "EDIT_PRIVILEGE\n" +
                "SORT\n" +
                "SEND_NOTICE\n" +
                "SHUT_UP\n" +
                "DISSOLVE\n" +
                "VIEW_GROUP_MEMBER\n" +
                "KICK_OUT_GROUP_MEMBER\n" +
                "SET_GROUP_MANAGER\n" +
                "ADD_GROUP_MEMBER\n" +
                "SHUT_UP_GROUP_MEMBER\n" +
                "SEND_MESSAGE\n" +
                "VIEW_FRIEND\n" +
                "ADD_FRIEND\n" +
                "DELETE_FRIEND\n" +
                "DELETE_ALL_FRIEND\n" +
                "VIEW_BLACKLIST\n" +
                "ADD_BLACKLIST\n" +
                "DELETE_BLACKLIST\n" +
                "KICK_OUT\n" +
                "REVOKE_MESSAGE\n" +
                "SUBMIT";

        String values = "阿富汗\n" +
                "阿爾巴尼亞\n" +
                "阿爾及利亞\n" +
                "美屬薩摩亞\n" +
                "安道爾\n" +
                "安哥拉\n" +
                "安圭拉\n" +
                "安提瓜和巴布達\n" +
                "阿根廷\n" +
                "亞美尼亞\n" +
                "阿魯巴\n" +
                "澳大利亞\n" +
                "奧地利\n" +
                "阿塞拜疆\n" +
                "巴哈馬\n" +
                "巴林\n" +
                "孟加拉國\n" +
                "巴巴多斯\n" +
                "白俄羅斯\n" +
                "比利時\n" +
                "伯利茲\n" +
                "貝寧\n" +
                "百慕大群島\n" +
                "不丹\n" +
                "玻利維亞\n" +
                "波斯尼亞和黑塞哥維那\n" +
                "博茨瓦納\n" +
                "巴西\n" +
                "文萊\n" +
                "保加利亞\n" +
                "布基納法索\n" +
                "布隆迪\n" +
                "柬埔寨\n" +
                "喀麥隆\n" +
                "加拿大\n" +
                "開普\n" +
                "開曼群島\n" +
                "中非共和國\n" +
                "乍得\n" +
                "智利\n" +
                "中國\n" +
                "哥倫比亞\n" +
                "科摩羅\n" +
                "庫克群島\n" +
                "哥斯達黎加\n" +
                "克羅地亞\n" +
                "古巴\n" +
                "庫拉索\n" +
                "塞浦路斯\n" +
                "捷克\n" +
                "剛果民主共和國\n" +
                "丹麥\n" +
                "吉布提\n" +
                "多米尼加\n" +
                "多米尼加共和國\n" +
                "東帝汶\n" +
                "厄瓜多爾\n" +
                "埃及\n" +
                "薩爾瓦多\n" +
                "赤道幾內亞\n" +
                "厄立特里亞\n" +
                "愛沙尼亞\n" +
                "埃塞俄比亞\n" +
                "法羅群島\n" +
                "斐濟\n" +
                "芬蘭\n" +
                "法國\n" +
                "法屬圭亞那\n" +
                "法屬波利尼西亞\n" +
                "加蓬\n" +
                "岡比亞\n" +
                "格魯吉亞\n" +
                "德國\n" +
                "加納\n" +
                "直布羅陀\n" +
                "希臘\n" +
                "格陵蘭島\n" +
                "格林納達\n" +
                "瓜德羅普島\n" +
                "關島\n" +
                "瓜地馬拉\n" +
                "幾內亞\n" +
                "幾內亞比紹共和國\n" +
                "圭亞那\n" +
                "海地\n" +
                "洪都拉斯\n" +
                "中國香港\n" +
                "匈牙利\n" +
                "冰島\n" +
                "印度\n" +
                "印度尼西亞\n" +
                "伊朗\n" +
                "伊拉克\n" +
                "愛爾蘭\n" +
                "以色列\n" +
                "意大利\n" +
                "象牙海岸\n" +
                "牙買加\n" +
                "日本\n" +
                "約旦\n" +
                "哈薩克斯坦\n" +
                "肯尼亞\n" +
                "基里巴斯\n" +
                "科威特\n" +
                "吉爾吉斯斯坦\n" +
                "老撾\n" +
                "拉脫維亞\n" +
                "黎巴嫩\n" +
                "萊索托\n" +
                "利比里亞\n" +
                "利比亞\n" +
                "列支敦士登\n" +
                "立陶宛\n" +
                "盧森堡\n" +
                "中國澳門\n" +
                "馬其頓\n" +
                "馬達加斯加\n" +
                "馬拉維\n" +
                "馬來西亞\n" +
                "馬爾代夫\n" +
                "馬里\n" +
                "馬耳他\n" +
                "馬提尼克\n" +
                "毛里塔尼亞\n" +
                "毛里求斯\n" +
                "馬約特\n" +
                "墨西哥\n" +
                "摩爾多瓦\n" +
                "摩納哥\n" +
                "蒙古\n" +
                "黑山\n" +
                "蒙特塞拉特島\n" +
                "摩洛哥\n" +
                "莫桑比克\n" +
                "緬甸\n" +
                "納米比亞\n" +
                "尼泊爾\n" +
                "荷蘭\n" +
                "新喀裡多尼亞\n" +
                "新西蘭\n" +
                "尼加拉瓜\n" +
                "尼日爾\n" +
                "尼日利亞\n" +
                "挪威\n" +
                "阿曼\n" +
                "巴基斯坦\n" +
                "帕勞\n" +
                "巴勒斯坦\n" +
                "巴拿馬\n" +
                "巴布亞新幾內亞\n" +
                "巴拉圭\n" +
                "秘魯\n" +
                "菲律賓\n" +
                "波蘭\n" +
                "葡萄牙\n" +
                "波多黎各\n" +
                "卡塔爾\n" +
                "剛果共和國\n" +
                "留尼汪\n" +
                "羅馬尼亞\n" +
                "俄羅斯\n" +
                "盧旺達\n" +
                "聖基茨和尼維斯\n" +
                "聖露西亞\n" +
                "聖彼埃爾和密克隆島\n" +
                "聖文森特和格林納丁斯\n" +
                "薩摩亞\n" +
                "聖馬力諾\n" +
                "聖多美和普林西比\n" +
                "沙特阿拉伯\n" +
                "塞內加爾\n" +
                "塞爾維亞\n" +
                "塞舌爾\n" +
                "塞拉利昂\n" +
                "新加坡\n" +
                "聖馬丁島（荷蘭部分）\n" +
                "斯洛伐克\n" +
                "斯洛文尼亞\n" +
                "所羅門群島\n" +
                "索馬里\n" +
                "南非\n" +
                "韓國\n" +
                "西班牙\n" +
                "斯里蘭卡\n" +
                "蘇丹\n" +
                "蘇里南\n" +
                "斯威士蘭\n" +
                "瑞典\n" +
                "瑞士\n" +
                "敘利亞\n" +
                "中國台灣\n" +
                "塔吉克斯坦\n" +
                "坦桑尼亞\n" +
                "泰國\n" +
                "多哥\n" +
                "湯加\n" +
                "特立尼達和多巴哥\n" +
                "突尼斯\n" +
                "土耳其\n" +
                "土庫曼斯坦\n" +
                "特克斯和凱科斯群島\n" +
                "烏干達\n" +
                "烏克蘭\n" +
                "阿拉伯聯合酋長國\n" +
                "英國\n" +
                "美國\n" +
                "烏拉圭\n" +
                "烏茲別克斯坦\n" +
                "瓦努阿圖\n" +
                "委內瑞拉\n" +
                "越南\n" +
                "英屬處女群島\n" +
                "美屬維爾京群島\n" +
                "也門\n" +
                "贊比亞\n" +
                "津巴布韋\n" +
                "密碼不能為空！\n" +
                "分頁參數錯誤！\n" +
                "用戶名不能為空！\n" +
                "參數錯誤\n" +
                "谷歌驗證碼不能為空！\n" +
                "TOKEN參數不能為空！\n" +
                "IP格式錯誤\n" +
                "時間戳參數不能為空！\n" +
                "時間戳參數已過期！\n" +
                "服務器繁忙，請稍候再試！\n" +
                "無此接口，請檢查！ （試試GET換成POST？）\n" +
                "Content-Type錯誤\n" +
                "您沒有權限訪問此功能！\n" +
                "功能未實現\n" +
                "請勿重複提交\n" +
                "請勿在該IP重複提交\n" +
                "請求排隊失敗，請稍候再試\n" +
                "參數{}丟失\n" +
                "非法請求\n" +
                "非法參數\n" +
                "請求正在處理中，請稍候再試！\n" +
                "請求超時\n" +
                "您的請求速度過快，請稍候再試！\n" +
                "數據狀態錯誤\n" +
                "該數據目前不可編輯！\n" +
                "該數據已被刪除！\n" +
                "數據已存在！\n" +
                "數據不存在！\n" +
                "數據不存在或已過期\n" +
                "您所在IP[{}]不允許操作！\n" +
                "IP[{}]不是有效IPV4/IPV4掩碼/IPV6格式\n" +
                "您所在區域[{}]不允許操作！\n" +
                "同一時間僅允許一次操作\n" +
                "已經是第一位了！\n" +
                "已經是最後一位了！\n" +
                "金額格式錯誤\n" +
                "金額不支持小數\n" +
                "金額格式錯誤，且最多{}位小數\n" +
                "金額不在{}範圍內\n" +
                "金額範圍格式錯誤\n" +
                "時間範圍格式錯誤\n" +
                "OSS連接錯誤{}\n" +
                "請選擇上傳文件\n" +
                "上傳文件出錯{}\n" +
                "上傳文件格式僅接受JPG或PNG\n" +
                "上傳大小超出最大限制{}\n" +
                "最多只能查詢過去{}天的數據\n" +
                "導出時間跨度最多{}天\n" +
                "請輸入備註\n" +
                "IM連接異常\n" +
                "IM執行異常，{}\n" +
                "角色名已經存在！\n" +
                "您只能操作您已擁有的角色或下級角色！\n" +
                "您只能操作下級角色！\n" +
                "您的賬號已被禁用，請聯繫客服！\n" +
                "您的賬號登錄權限已被禁用，請聯繫客服！\n" +
                "您的賬號充值權限已被禁用，請聯繫客服！\n" +
                "您的賬號提現權限已被禁用，請聯繫客服！\n" +
                "您已經登錄！\n" +
                "用戶名或密碼錯誤！\n" +
                "用戶名或密碼錯誤，還剩{}機會！\n" +
                "登錄密碼錯誤次數過多，請聯繫管理員重置！\n" +
                "角色已被禁用！\n" +
                "非法角色！\n" +
                "用戶不存在！\n" +
                "用戶餘額不足\n" +
                "谷歌驗證碼錯誤！\n" +
                "每組驗證碼只允許使用1次，請稍候再試\n" +
                "您已綁定谷歌身份驗證器，無需再次綁定！\n" +
                "請先綁定谷歌身份驗證器！\n" +
                "用戶名已存在！\n" +
                "不允許操作自己！\n" +
                "不允許操作管理員！\n" +
                "您已被強制登出！\n" +
                "您的賬號在別處登錄，請重新登錄！\n" +
                "您的賬號信息發生變化，請重新登錄！\n" +
                "會話失效，請重新登錄！\n" +
                "會話過期，請重新登錄！\n" +
                "請先登錄！\n" +
                "token參數不能為空！\n" +
                "token無效！\n" +
                "舊密碼輸入錯誤！\n" +
                "您已設置該密碼，無需再次設置！\n" +
                "新舊密碼不能一致！\n" +
                "請先設置資金密碼！\n" +
                "資金密碼錯誤！\n" +
                "資金密碼不允許和登錄密碼一致！\n" +
                "用戶充值權限不可用！\n" +
                "用戶提現權限不可用！\n" +
                "註冊鏈接最多生成{}個，請調整\n" +
                "註冊入口已關閉，請聯繫客服\n" +
                "該IP[{}]註冊用戶數超過限制\n" +
                "請輸入邀請碼\n" +
                "邀請碼錯誤，請重新輸入\n" +
                "邀請碼不可用，請重新輸入\n" +
                "請輸入手機\n" +
                "該手機號已註冊\n" +
                "請輸入手機驗證碼\n" +
                "請輸入資金密碼\n" +
                "邀請碼不存在\n" +
                "提現姓名必須為中文\n" +
                "您已綁定提現姓名，無需再次綁定\n" +
                "請先綁定提現姓名\n" +
                "對方還不是您的好友\n" +
                "未找到可用的銀行卡，請選擇其它充值方式\n" +
                "請輸入付款人\n" +
                "每日最多允許提交{}筆提現訂單\n" +
                "同時最多允許提交{}筆提現訂單\n" +
                "您當前還需消費≈{}:{}金額的虛擬貨幣，才可提現\n" +
                "當前已過提現時間：{}\n" +
                "未找到該三方配置，或已被刪除\n" +
                "三方配置格式錯誤\n" +
                "未找到該三方充值處理類\n" +
                "請求三方充值異常，{}\n" +
                "請求三方充值返回錯誤，{}\n" +
                "回調處理失敗\n" +
                "未找到該API代付配置，或已被刪除\n" +
                "三方配置格式錯誤\n" +
                "該API代付配置已被禁用\n" +
                "未找到該API代付處理類\n" +
                "請求API代付異常，{}\n" +
                "請求API代付返回錯誤，{}\n" +
                "回調處理失敗\n" +
                "銀行不存在\n" +
                "銀行已被禁用\n" +
                "銀行名已存在\n" +
                "銀行名編碼存在\n" +
                "卡號{}已被列入黑名單，無法處理\n" +
                "卡號已存在\n" +
                "請選擇銀行卡\n" +
                "提現銀行已被禁用\n" +
                "最多允許綁定{}張銀行卡，您目前已綁定{}張\n" +
                "請先綁定銀行卡\n" +
                "未找到您綁定的銀行卡信息\n" +
                "該銀行卡目前不可用\n" +
                "朋友圈最多發布9張圖片\n" +
                "您沒有權限查看\n" +
                "請選擇允許查看的好友\n" +
                "請選擇拒絕查看的好友\n" +
                "最多允許查詢過去{}天數據，請重試\n" +
                "日期選擇錯誤，請重試\n" +
                "用戶{}不是直屬下級或者不存在，無法查詢，請重試\n" +
                "沒有可用語言！\n" +
                "該語言不可用！\n" +
                "該紅包已過期\n" +
                "該紅包已被領取\n" +
                "該紅包已被領取完\n" +
                "不能給自己發紅包\n" +
                "群紅包個數最多拆分{}個\n" +
                "平均金額必須範圍必須為{}\n" +
                "用戶已經在群組中，無需添加！\n" +
                "只能刪除一天內的消息，請重新選擇！\n" +
                "您不在群組中\n" +
                "全員禁言中，無法發言\n" +
                "您被禁言中，無法發言\n" +
                "短信服務連接異常，請選擇其它方式或聯繫客服\n" +
                "短信服務連接失敗，{}，請選擇其它方式或聯繫客服\n" +
                "驗證碼過期\n" +
                "驗證碼錯誤\n" +
                "不支持該國家\n" +
                "應用數字版本號必須遞增\n" +
                "報表管理\n" +
                "用戶管理\n" +
                "支付管理\n" +
                "紅包管理\n" +
                "用戶群組\n" +
                "公告管理\n" +
                "系統管理\n" +
                "後台管理\n" +
                "用戶登錄日誌\n" +
                "用戶操作日誌\n" +
                "用戶賬變\n" +
                "用戶卡黑名單\n" +
                "用戶區域黑白名單\n" +
                "用戶IP黑白名單\n" +
                "用戶餘額快照\n" +
                "用戶銀行卡\n" +
                "朋友圈管理\n" +
                "充值訂單\n" +
                "提現訂單\n" +
                "銀行卡充值配置\n" +
                "三方充值配置\n" +
                "銀行卡提現配置\n" +
                "API代付配置\n" +
                "個人紅包\n" +
                "群紅包\n" +
                "群組管理\n" +
                "用戶通訊錄\n" +
                "在線用戶\n" +
                "單聊消息\n" +
                "群聊消息\n" +
                "系統配置\n" +
                "系統高級配置\n" +
                "系統備份配置\n" +
                "銀行管理\n" +
                "數據遷移\n" +
                "應用版本管理\n" +
                "後台用戶管理\n" +
                "後台角色管理\n" +
                "後台菜單管理\n" +
                "後台登錄日誌\n" +
                "後台操作日誌\n" +
                "後台IP黑白名單\n" +
                "列表\n" +
                "新增\n" +
                "編輯\n" +
                "啟/禁登錄\n" +
                "啟/禁加好友\n" +
                "啟/禁充值\n" +
                "啟/禁提現\n" +
                "重置資金密碼\n" +
                "編輯提現姓名\n" +
                "導出\n" +
                "刪除\n" +
                "啟/禁\n" +
                "刪除評論\n" +
                "刪除點贊\n" +
                "補單\n" +
                "人工充值\n" +
                "審核\n" +
                "打款\n" +
                "人工提現\n" +
                "解綁谷歌\n" +
                "重置密碼錯誤次數\n" +
                "編輯權限\n" +
                "排序\n" +
                "發送通知\n" +
                "禁言\n" +
                "解散\n" +
                "查看群成員\n" +
                "踢出群成員\n" +
                "設置管理員\n" +
                "新增群成員\n" +
                "禁言群成員\n" +
                "發送消息\n" +
                "查看好友\n" +
                "新增好友\n" +
                "刪除好友\n" +
                "刪除所有好友\n" +
                "查看黑名單\n" +
                "新增黑名單\n" +
                "刪除黑名單\n" +
                "踢下線\n" +
                "撤回消息\n" +
                "提交";

        String[] groupArr = groups.split("\n");
        String[] codeArr = codes.split("\n");
        String[] valueArr = values.split("\n");

        String sqlTemp = "INSERT INTO `i18n_translate` (`id`, `group`, `key`, `language_code`, `value`, `create_time`, `update_time`)\t" +
                "VALUES\t" +
                "(NULL, '{}', '{}', 'zh-HK', '{}', '2020-05-27 14:54:19', '2020-05-27 14:54:19');";

        for (int i = 0; i < groupArr.length; i++) {
            String group = groupArr[i];
            String code = codeArr[i];
            String value = valueArr[i];

            String sql = StrUtil.format(sqlTemp, group, code, value);
            System.out.println(sql);
        }
    }
}
